/**
 * Trulioo JavaScript SDK
 *
 * Package version: 1.0.2
 * Trulioo OpenAPI version: v1
 * Generated by OpenAPI Generator version: 5.0.1
 */
import ApiClient from '../ApiClient';
import BusinessRecord from './BusinessRecord';
import ServiceError from './ServiceError';

/**
 * The BusinessSearchResponse model module.
 * @module model/BusinessSearchResponse
 * @version v1
 */
class BusinessSearchResponse {
    /**
     * Constructs a new <code>BusinessSearchResponse</code>.
     * @alias module:model/BusinessSearchResponse
     */
    constructor() { 
        
        BusinessSearchResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BusinessSearchResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BusinessSearchResponse} obj Optional instance to populate.
     * @return {module:model/BusinessSearchResponse} The populated <code>BusinessSearchResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BusinessSearchResponse();

            if (data.hasOwnProperty('TransactionID')) {
                obj['TransactionID'] = ApiClient.convertToType(data['TransactionID'], 'String');
            }
            if (data.hasOwnProperty('UploadedDt')) {
                obj['UploadedDt'] = ApiClient.convertToType(data['UploadedDt'], 'Date');
            }
            if (data.hasOwnProperty('CountryCode')) {
                obj['CountryCode'] = ApiClient.convertToType(data['CountryCode'], 'String');
            }
            if (data.hasOwnProperty('ProductName')) {
                obj['ProductName'] = ApiClient.convertToType(data['ProductName'], 'String');
            }
            if (data.hasOwnProperty('Record')) {
                obj['Record'] = BusinessRecord.constructFromObject(data['Record']);
            }
            if (data.hasOwnProperty('Errors')) {
                obj['Errors'] = ApiClient.convertToType(data['Errors'], [ServiceError]);
            }
        }
        return obj;
    }


}

/**
 * The id for the transaction it will be a GUID
 * @member {String} TransactionID
 */
BusinessSearchResponse.prototype['TransactionID'] = undefined;

/**
 * Time in UTC
 * @member {Date} UploadedDt
 */
BusinessSearchResponse.prototype['UploadedDt'] = undefined;

/**
 * The country code for which the verification was performed.
 * @member {String} CountryCode
 */
BusinessSearchResponse.prototype['CountryCode'] = undefined;

/**
 * Product Name
 * @member {String} ProductName
 */
BusinessSearchResponse.prototype['ProductName'] = undefined;

/**
 * @member {module:model/BusinessRecord} Record
 */
BusinessSearchResponse.prototype['Record'] = undefined;

/**
 * Collection of record errors
 * @member {Array.<module:model/ServiceError>} Errors
 */
BusinessSearchResponse.prototype['Errors'] = undefined;






export default BusinessSearchResponse;

