/**
 * Trulioo JavaScript SDK
 *
 * Package version: 1.0.3
 * Trulioo OpenAPI version: v1
 * Generated by OpenAPI Generator version: 5.0.1
 */
import ApiClient from '../ApiClient';

/**
 * The BusinessRegistrationNumberMask model module.
 * @module model/BusinessRegistrationNumberMask
 * @version v1
 */
class BusinessRegistrationNumberMask {
    /**
     * Constructs a new <code>BusinessRegistrationNumberMask</code>.
     * @alias module:model/BusinessRegistrationNumberMask
     */
    constructor() { 
        
        BusinessRegistrationNumberMask.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BusinessRegistrationNumberMask</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BusinessRegistrationNumberMask} obj Optional instance to populate.
     * @return {module:model/BusinessRegistrationNumberMask} The populated <code>BusinessRegistrationNumberMask</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BusinessRegistrationNumberMask();

            if (data.hasOwnProperty('Mask')) {
                obj['Mask'] = ApiClient.convertToType(data['Mask'], 'String');
            }
            if (data.hasOwnProperty('IgnoreWhitespace')) {
                obj['IgnoreWhitespace'] = ApiClient.convertToType(data['IgnoreWhitespace'], 'Boolean');
            }
            if (data.hasOwnProperty('IgnoreSpecialCharacter')) {
                obj['IgnoreSpecialCharacter'] = ApiClient.convertToType(data['IgnoreSpecialCharacter'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * The mask used to validate the format of the business registration number
 * @member {String} Mask
 */
BusinessRegistrationNumberMask.prototype['Mask'] = undefined;

/**
 * Flag showing whether we can ignore whitespace
 * @member {Boolean} IgnoreWhitespace
 */
BusinessRegistrationNumberMask.prototype['IgnoreWhitespace'] = undefined;

/**
 * Flag showing whether we can ignore special character
 * @member {Boolean} IgnoreSpecialCharacter
 */
BusinessRegistrationNumberMask.prototype['IgnoreSpecialCharacter'] = undefined;






export default BusinessRegistrationNumberMask;

