/**
 * Trulioo JavaScript SDK
 *
 * Package version: 1.0.1
 * Trulioo OpenAPI version: v1
 * Generated by OpenAPI Generator version: 5.0.1
 */
import ApiClient from '../ApiClient';
import BusinessResult from './BusinessResult';
import ServiceError from './ServiceError';

/**
 * The BusinessRecord model module.
 * @module model/BusinessRecord
 * @version v1
 */
class BusinessRecord {
    /**
     * Constructs a new <code>BusinessRecord</code>.
     * @alias module:model/BusinessRecord
     */
    constructor() { 
        
        BusinessRecord.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BusinessRecord</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BusinessRecord} obj Optional instance to populate.
     * @return {module:model/BusinessRecord} The populated <code>BusinessRecord</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BusinessRecord();

            if (data.hasOwnProperty('TransactionRecordID')) {
                obj['TransactionRecordID'] = ApiClient.convertToType(data['TransactionRecordID'], 'String');
            }
            if (data.hasOwnProperty('RecordStatus')) {
                obj['RecordStatus'] = ApiClient.convertToType(data['RecordStatus'], 'String');
            }
            if (data.hasOwnProperty('DatasourceResults')) {
                obj['DatasourceResults'] = ApiClient.convertToType(data['DatasourceResults'], [BusinessResult]);
            }
            if (data.hasOwnProperty('Errors')) {
                obj['Errors'] = ApiClient.convertToType(data['Errors'], [ServiceError]);
            }
        }
        return obj;
    }


}

/**
 * The TransactionRecordID, this is the ID you will use to fetch the transaction again.
 * @member {String} TransactionRecordID
 */
BusinessRecord.prototype['TransactionRecordID'] = undefined;

/**
 * 'match' or 'nomatch' if the verification passed the rules configured on your account this will be 'match'.
 * @member {String} RecordStatus
 */
BusinessRecord.prototype['RecordStatus'] = undefined;

/**
 * Results for each datasource that was queried
 * @member {Array.<module:model/BusinessResult>} DatasourceResults
 */
BusinessRecord.prototype['DatasourceResults'] = undefined;

/**
 * @member {Array.<module:model/ServiceError>} Errors
 */
BusinessRecord.prototype['Errors'] = undefined;






export default BusinessRecord;

