/**
 * Trulioo JavaScript SDK
 *
 * Package version: 1.0.2
 * Trulioo OpenAPI version: v1
 * Generated by OpenAPI Generator version: 5.0.1
 */
import ApiClient from '../ApiClient';
import BusinessRegistrationNumberMask from './BusinessRegistrationNumberMask';

/**
 * The BusinessRegistrationNumber model module.
 * @module model/BusinessRegistrationNumber
 * @version v1
 */
class BusinessRegistrationNumber {
    /**
     * Constructs a new <code>BusinessRegistrationNumber</code>.
     * @alias module:model/BusinessRegistrationNumber
     */
    constructor() { 
        
        BusinessRegistrationNumber.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BusinessRegistrationNumber</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BusinessRegistrationNumber} obj Optional instance to populate.
     * @return {module:model/BusinessRegistrationNumber} The populated <code>BusinessRegistrationNumber</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BusinessRegistrationNumber();

            if (data.hasOwnProperty('Name')) {
                obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
            }
            if (data.hasOwnProperty('Description')) {
                obj['Description'] = ApiClient.convertToType(data['Description'], 'String');
            }
            if (data.hasOwnProperty('Country')) {
                obj['Country'] = ApiClient.convertToType(data['Country'], 'String');
            }
            if (data.hasOwnProperty('Jurisdiction')) {
                obj['Jurisdiction'] = ApiClient.convertToType(data['Jurisdiction'], 'String');
            }
            if (data.hasOwnProperty('Supported')) {
                obj['Supported'] = ApiClient.convertToType(data['Supported'], 'Boolean');
            }
            if (data.hasOwnProperty('Type')) {
                obj['Type'] = ApiClient.convertToType(data['Type'], 'String');
            }
            if (data.hasOwnProperty('Masks')) {
                obj['Masks'] = ApiClient.convertToType(data['Masks'], [BusinessRegistrationNumberMask]);
            }
        }
        return obj;
    }


}

/**
 * The name of the business registration number
 * @member {String} Name
 */
BusinessRegistrationNumber.prototype['Name'] = undefined;

/**
 * Brief description of the business registration number
 * @member {String} Description
 */
BusinessRegistrationNumber.prototype['Description'] = undefined;

/**
 * Country to which the business registration number applies
 * @member {String} Country
 */
BusinessRegistrationNumber.prototype['Country'] = undefined;

/**
 * Optional jurisdiction to which the business registration number applies
 * @member {String} Jurisdiction
 */
BusinessRegistrationNumber.prototype['Jurisdiction'] = undefined;

/**
 * Whether the business registration number is supported by Trulioo's systems
 * @member {Boolean} Supported
 */
BusinessRegistrationNumber.prototype['Supported'] = undefined;

/**
 * The specified type of this business registration number
 * @member {String} Type
 */
BusinessRegistrationNumber.prototype['Type'] = undefined;

/**
 * The mask(s) describing this business registration number
 * @member {Array.<module:model/BusinessRegistrationNumberMask>} Masks
 */
BusinessRegistrationNumber.prototype['Masks'] = undefined;






export default BusinessRegistrationNumber;

