/**
 * Trulioo JavaScript SDK
 *
 * Package version: 1.0.3
 * Trulioo OpenAPI version: v1
 * Generated by OpenAPI Generator version: 5.0.1
 */
import ApiClient from '../ApiClient';
import Result from './Result';
import ServiceError from './ServiceError';

/**
 * The BusinessResult model module.
 * @module model/BusinessResult
 * @version v1
 */
class BusinessResult {
    /**
     * Constructs a new <code>BusinessResult</code>.
     * @alias module:model/BusinessResult
     */
    constructor() { 
        
        BusinessResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BusinessResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BusinessResult} obj Optional instance to populate.
     * @return {module:model/BusinessResult} The populated <code>BusinessResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BusinessResult();

            if (data.hasOwnProperty('Results')) {
                obj['Results'] = ApiClient.convertToType(data['Results'], [Result]);
            }
            if (data.hasOwnProperty('DatasourceName')) {
                obj['DatasourceName'] = ApiClient.convertToType(data['DatasourceName'], 'String');
            }
            if (data.hasOwnProperty('Errors')) {
                obj['Errors'] = ApiClient.convertToType(data['Errors'], [ServiceError]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Result>} Results
 */
BusinessResult.prototype['Results'] = undefined;

/**
 * @member {String} DatasourceName
 */
BusinessResult.prototype['DatasourceName'] = undefined;

/**
 * @member {Array.<module:model/ServiceError>} Errors
 */
BusinessResult.prototype['Errors'] = undefined;






export default BusinessResult;

