/**
 * Trulioo JavaScript SDK
 *
 * Package version: 1.0.2
 * Trulioo OpenAPI version: v1
 * Generated by OpenAPI Generator version: 5.0.1
 */
import ApiClient from '../ApiClient';

/**
 * The Document model module.
 * @module model/Document
 * @version v1
 */
class Document {
    /**
     * Constructs a new <code>Document</code>.
     * @alias module:model/Document
     */
    constructor() { 
        
        Document.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Document</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Document} obj Optional instance to populate.
     * @return {module:model/Document} The populated <code>Document</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Document();

            if (data.hasOwnProperty('DocumentFrontImage')) {
                obj['DocumentFrontImage'] = ApiClient.convertToType(data['DocumentFrontImage'], 'Blob');
            }
            if (data.hasOwnProperty('DocumentBackImage')) {
                obj['DocumentBackImage'] = ApiClient.convertToType(data['DocumentBackImage'], 'Blob');
            }
            if (data.hasOwnProperty('LivePhoto')) {
                obj['LivePhoto'] = ApiClient.convertToType(data['LivePhoto'], 'Blob');
            }
            if (data.hasOwnProperty('DocumentType')) {
                obj['DocumentType'] = ApiClient.convertToType(data['DocumentType'], 'String');
            }
            if (data.hasOwnProperty('AcceptIncompleteDocument')) {
                obj['AcceptIncompleteDocument'] = ApiClient.convertToType(data['AcceptIncompleteDocument'], 'Boolean');
            }
            if (data.hasOwnProperty('ValidateDocumentImageQuality')) {
                obj['ValidateDocumentImageQuality'] = ApiClient.convertToType(data['ValidateDocumentImageQuality'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * Front of the document
 * @member {Blob} DocumentFrontImage
 */
Document.prototype['DocumentFrontImage'] = undefined;

/**
 * Back of the document
 * @member {Blob} DocumentBackImage
 */
Document.prototype['DocumentBackImage'] = undefined;

/**
 * Selfie image
 * @member {Blob} LivePhoto
 */
Document.prototype['LivePhoto'] = undefined;

/**
 * Document type
 * @member {String} DocumentType
 */
Document.prototype['DocumentType'] = undefined;

/**
 * Accept Incomplete Document
 * @member {Boolean} AcceptIncompleteDocument
 */
Document.prototype['AcceptIncompleteDocument'] = undefined;

/**
 * Validate Document Image Quality
 * @member {Boolean} ValidateDocumentImageQuality
 */
Document.prototype['ValidateDocumentImageQuality'] = undefined;






export default Document;

