/**
 * Trulioo JavaScript SDK
 *
 * Package version: 1.0.2
 * Trulioo OpenAPI version: v1
 * Generated by OpenAPI Generator version: 5.0.1
 */

import ApiClient from "../ApiClient";

/**
* WorldCheck service.
* @module api/WorldCheckApi
* @version v1
*/
export default class WorldCheckApi {

    /**
    * Constructs a new WorldCheckApi. 
    * @alias module:api/WorldCheckApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Get World Check Profile
     * Returns the corresponding world-check profile of the specified transaction ID and reference ID.
     * @param {String} mode trial or live
     * @param {String} originalTransactionID 
     * @param {String} referenceID 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    getWorldCheckProfileWithHttpInfo(mode, originalTransactionID, referenceID) {
      let postBody = null;
      // verify the required parameter 'mode' is set
      if (mode === undefined || mode === null) {
        throw new Error("Missing the required parameter 'mode' when calling getWorldCheckProfile");
      }
      // verify the required parameter 'originalTransactionID' is set
      if (originalTransactionID === undefined || originalTransactionID === null) {
        throw new Error("Missing the required parameter 'originalTransactionID' when calling getWorldCheckProfile");
      }
      // verify the required parameter 'referenceID' is set
      if (referenceID === undefined || referenceID === null) {
        throw new Error("Missing the required parameter 'referenceID' when calling getWorldCheckProfile");
      }

      let pathParams = {
        'mode': mode,
        'originalTransactionID': originalTransactionID,
        'referenceID': referenceID
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json', 'text/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/{mode}/worldcheck/v1/profile/{originalTransactionID}/{referenceID}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get World Check Profile
     * Returns the corresponding world-check profile of the specified transaction ID and reference ID.
     * @param {String} mode trial or live
     * @param {String} originalTransactionID 
     * @param {String} referenceID 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    getWorldCheckProfile(mode, originalTransactionID, referenceID) {
      return this.getWorldCheckProfileWithHttpInfo(mode, originalTransactionID, referenceID)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
